"""As-built configuration: turn what is actually installed into an astra.toml."""

from __future__ import annotations

from astra.config import AstraConfig
from astra.hardware.compat import analyse
from astra.hardware.models import Inventory
from astra.units import MIB


def render_config(inv: Inventory, cfg: AstraConfig) -> str:
    """astra.toml that freezes the currently installed chassis GPUs as the as-built node."""
    report = analyse(
        inv.gpus, inv.driver_version, cfg.chassis, inv.paths, cfg.interconnect.switch_vendor_ids
    )
    lines = [
        f"# generated by `astra probe --emit-config` ({report.chassis_basis})",
        "[node]",
        f'name = "{cfg.node.name}"',
        "",
    ]
    for c in report.chassis:
        model = c.spec.model if c.spec else c.gpu.name.replace("NVIDIA GeForce ", "")
        lines += ["[[node.expected_gpu]]", f'match = "{model}"']
        if c.gpu.memory_total_bytes:
            lines.append(f"vram_mib = {c.gpu.memory_total_bytes // MIB}")
        lines.append("")
    lines += [
        "[chassis]",
        f"psu_watts = {cfg.chassis.psu_watts}  # these GPUs need >= "
        f"{report.power.recommended_psu_watts} W",
        f"slots = {cfg.chassis.slots}",
        "",
    ]
    lines += topology_config(inv, cfg, [c.gpu.uuid for c in report.chassis])
    return "\n".join(lines) + "\n"


def topology_config(inv: Inventory, cfg: AstraConfig, uuids: list[str]) -> list[str]:
    """[interconnect] matching what is plugged in: switch or not, narrowest link."""
    paths = [inv.paths[u] for u in uuids if u in inv.paths]
    if not paths and inv.gpu_links:
        from astra.hardware.nvtopo import SWITCH_LINKS

        shared = all(v in SWITCH_LINKS for v in inv.gpu_links.values())
        return [
            "[interconnect]",
            "# detected with nvidia-smi topo: "
            + ("GPUs share a PCIe switch" if shared else "GPUs connect through the CPU"),
            f"require_switch = {str(shared).lower()}",
        ]
    if not paths:
        return [
            "[interconnect]",
            "# PCIe topology not visible here (needs Linux sysfs); defaults kept.",
            f"require_switch = {str(cfg.interconnect.require_switch).lower()}",
        ]
    vendors = cfg.interconnect.switch_vendor_ids
    has_switch = any(p.switches(vendors) for p in paths)
    hops = [p.bottleneck for p in paths if p.bottleneck is not None]
    width = min((h.current_width or 16) for h in hops) if hops else 16
    # The link can only train as fast as the slowest device on it (e.g. a Gen3 switch).
    gens = [h.max_gen for p in paths for h in p.chain if h.max_gen]
    gen = min(gens) if gens else 3
    kind = "PCIe switch" if has_switch else "direct slots / bifurcation / adapters"
    return [
        "[interconnect]",
        f"# detected: {kind}; narrowest link Gen{gen} x{width}",
        f"require_switch = {str(has_switch).lower()}",
        f"expected_uplink_gen = {gen}",
        f"expected_uplink_width = {width}",
    ]
